KablamoOSS/kerosene

- package.json
- packages/kerosene/package.json
- packages/kerosene/readme.md
- packages/kerosene/src/fetch/isNetworkError.spec.ts
- packages/kerosene/src/fetch/isNetworkError.ts
- packages/kerosene/src/fetch/transform.spec.ts
- packages/kerosene/src/fetch/transform.ts
- packages/kerosene/src/fetch/transformAndCheckStatus.spec.ts
- packages/kerosene/src/fetch/transformAndCheckStatus.ts
- packages/kerosene/src/index.ts
- readme.md
- yarn.lock
Adds:
- `isNetworkError`
- `transform`
- `transformAndCheckStatus`
Wait for #17 to be merged first.
> Fetch-related utils

- packages/kerosene-ui/package.json
- packages/kerosene-ui/src/index.ts
Fix `usInterval` -> `useInterval` typo.
Export `SafeAreaInsets`.
> kerosene-ui: Fix exports and bump version

- packages/kerosene/package.json
- packages/kerosene/src/array/product.ts
- yarn.lock
Adds some overload signatures for `product()` that provide stricter typings for consumers.
> kerosene: Stricter typings for product()

- packages/kerosene/package.json
- packages/kerosene/readme.md
- packages/kerosene/src/types/index.ts
Adds the `KeysWhere<T, TValue>` utlity type which creates a union of all keys of `T` where `T[key]` has type `TValue`.
> kerosene: Add KeysWhere<T, TValue> utility type

- packages/kerosene/package.json
- packages/kerosene/readme.md
- packages/kerosene/src/types/index.ts
Adds a `MergedUnion<T>` utility type that, from a union type `T`, allows properties which are not shared by all members to be `undefined`.
> kerosene: Add MergedUnion<T> type

- packages/kerosene/package.json
- packages/kerosene/readme.md
- packages/kerosene/src/types/index.ts
Adds an `Entries<T>` utility type which infers the union of all object entry tuples for type `T`.
Also updates `ElementType<TCollection>` to infer the value type for plain objects.
> kerosene: Add Entries<T> utility type, update ElementType<TCollection> to accept plain objects

- packages/kerosene-ui/package.json
- packages/kerosene-ui/src/hooks/useRect.spec.tsx
- packages/kerosene-ui/src/hooks/useRect.ts
useRect is a custom hook for reading the bounding rect of an element
We are using the bounding rect of a component to resize an svg within it
The rect was only updating on window resize and scroll events, we needed our component to update and resize after css transitions on the page
This PR extends useRect() so we can specify events like "transitionend" to trigger and update
> extend useRect to update for specified event

- packages/kerosene-ui/package.json
- packages/kerosene-ui/readme.md
- packages/kerosene-ui/src/index.ts
- packages/kerosene-ui/src/utils/measureCSSProperty.spec.ts
- packages/kerosene-ui/src/utils/measureCSSProperty.ts
- yarn.lock
Adds a `measureCSSProperty(element, property, value)` function which injects a `<noscript />` element at the provided `element` and applies the `value` for the `property`. This is useful for probing the value of a CSS custom property that contains a calc expression at a given point in the DOM.
> kerosene-ui: Add measureCSSProperty function

- packages/kerosene-ui/package.json
- packages/kerosene-ui/src/hooks/useRect.spec.tsx
- packages/kerosene-ui/src/hooks/useRect.ts
- Ensures that listeners are added/removed when the `eventList` changes
- Allows `eventList` parameter to accept a `readonly` array.
> kerosene-ui: Fix useRect eventList

- packages/kerosene-test/package.json
- packages/kerosene-test/src/react/createStubComponent.tsx
This is useful for snapshot testing, where only the underlying DOM is represented. This will ensure that the correct component is rendered once compared to the snapshot.
> Add Display Name to the underlying DOM

- packages/kerosene-test/package.json
- packages/kerosene-test/src/react/createStubComponent.tsx
> kerosene-test: createStubComponent - pass props to getRenderProps

- .github/workflows/nodejs.yml
~~I think `needs` was required in order for more than one job to run.~~
`if: github.ref == 'refs/heads/master'` was required
> Fix release workflow

- packages/eslint-plugin/package.json
- packages/kerosene-feature-flags/.npmignore
- packages/kerosene-styles/.npmignore
- packages/kerosene-test/.npmignore
- packages/kerosene-test/package.json
- packages/kerosene-ui/.npmignore
- packages/kerosene/.npmignore
It looks like the last release of `@kablamo/kerosene-test` was missing the `.dist` folder due to `@changsets/cli` not accounting for the `.npmignore` file at a top level (which should have overridden the `.gitignore` file).
Bumping the version should trigger a re-publish with the correct files, and future publishes of other packages should happen correctly.
> kerosene-test: Fix publishing .dist

- packages/kerosene-ui/package.json
- packages/kerosene/package.json
- packages/kerosene/src/datetime/constants.ts
- packages/kerosene/src/datetime/getCalendarWeeks.ts
- packages/kerosene/src/datetime/index.ts
~~Depending on kerosene seemed to blow up the CRA minifier due to circular dependencies in sourcemaps~~. This turned out to be a red herring and CRA was just choking on source maps inside node_modules in general. Found an actual workaround here https://github.com/facebook/create-react-app/issues/8071#issuecomment-566257193
> kerosene: fix circular dependency

- packages/kerosene-ui/package.json
- packages/kerosene-ui/src/types/index.ts
Read about this technique in the discussion for TypeScript's new `awaited` type operator when they were considering just a utility type: https://github.com/microsoft/TypeScript/pull/35998
This appears to trick TS into lazily evaluating the types which avoids infinite recursion, which isn't permitted.
> kerosene-ui: Make UnwrapComponent utlity type actually recursive

- .github/workflows/nodejs.yml
- packages/kerosene-test/package.json
- packages/kerosene-ui/package.json
- packages/kerosene/package.json
- packages/kerosene/src/datetime/getCalendarWeeks.spec.ts
- yarn.lock
This previously went unnoticed as `@kablamo/kerosene-ui` depends on `@kablamo/kerosene` which itself depends on `lodash`. Yarn v2 is enforcing dependencies more strictly which surfaced this.
> kerosene-ui: Add missing lodash dependency

- packages/kerosene-ui/package.json
- packages/kerosene/package.json
- packages/kerosene/readme.md
- packages/kerosene/src/string/parseSearch.ts
Also replaces wildcard import of `querystring` with default import to work around faulty polyfill with ESBuild
> kerosene: deprecate parseSearch

- packages/eslint-config/index.js
- packages/eslint-config/package.json
Fixes error with `react/no-unknown-property` and Emotion `css` prop
> eslint-config: Allow Emotion css prop

- packages/kerosene-ui/package.json
- packages/kerosene/package.json
- packages/kerosene/src/function/waitForEventLoopToDrain.ts
Was previously thinking about using `package.json` exports to define something different for Node and the browser, but `jest-environment-jsdom` now uses the browser resolution for packages which rendered that approach no longer viable.
Instead, we can check for the presence of `jest.requireActual` if `globalThis.setImmediate` is not available to determine if we're in a jest environment, and require the actual, unstubbed Node [`timers`](https://nodejs.org/api/timers.html#setimmediatecallback-args) module. Thankfully, unlike `require`, `jest.requireActual` should be ignored by bundlers like `esbuild`, `webpack` and `rollup` and should not result in Node requires in code that is intended for browsers.
> kerosene: Fix waitForEventLoopToDrain breaking in Jest

- packages/kerosene-test/package.json
- packages/kerosene-test/readme.md
- packages/kerosene-test/src/jest/index.ts
- packages/kerosene-test/src/sinon/index.ts
- packages/kerosene-ui/package.json
- packages/kerosene/package.json
- packages/kerosene/readme.md
- packages/kerosene/src/types/index.ts
Adds utility types for `Overloads<T>`, `OverloadedParameters<T>`, `OverloadedReturnType<T>`, `OverloadedReturnTypeWhen<T, P>`.
> kerosene: Add overload utility types

- packages/kerosene/rollup-config.ts
- packages/kerosene/src/string/parseSearch.ts
The dependency on `querystring` was causing deprecation notices to be included, even when consuming projects did not use the deprecated `parseSearch` function. As a result, this has been rewritten to be API-compatible but using the `URLSearchParams` as the parser to avoid the deprecation notice being included.
We should remove `parseSearch` entirely from a future version of `kerosene`.
> kerosene: Remove querystring dependency from parseSearch

- .github/workflows/nodejs.yml
- packages/kerosene-ui/package.json
- packages/kerosene-ui/readme.md
- packages/kerosene-ui/src/hooks/useCurrentTime.spec.tsx
- packages/kerosene-ui/src/hooks/useCurrentTime.tsx
- packages/kerosene-ui/src/hooks/useIsomorphicLayoutEffect.ts
- packages/kerosene-ui/src/hooks/useLocalStorage.spec.tsx
- packages/kerosene-ui/src/hooks/useLocalStorage.ts
- packages/kerosene-ui/src/hooks/useMediaQuery.spec.ts
- packages/kerosene-ui/src/hooks/useMediaQuery.ts
- packages/kerosene-ui/src/hooks/usePageVisibility.spec.tsx
- packages/kerosene-ui/src/hooks/usePageVisibility.ts
- packages/kerosene-ui/src/index.ts
- yarn.lock
> kerosene-ui: Add useLocalStorage hook, and use useSyncExternalStore for useMediaQuery, usePageVisibility

- packages/kerosene-ui/package.json
- packages/kerosene-ui/readme.md
- packages/kerosene-ui/src/hooks/useTimeZone.spec.tsx
- packages/kerosene-ui/src/hooks/useTimeZone.tsx
> kerosene-ui: Add useTimeZone hook

- packages/eslint-config/index.js
- packages/eslint-config/package.json
Ran into an issue when updating to the latest version of eslint-config:
```
Error: Error while loading rule '@typescript-eslint/naming-convention': You have used a rule which requires parserServices to be generated. You must therefore provide a value for the "parserOptions.project" property for @typescript-eslint/parser.
Occurred while linting /Users/will/code/kablamo/os/os-frontend/packages/design-system/src/docs/Cheatsheet.mdx
```
@nhardy found that the naming-convention rule requires type information, so this rule should only be enabled on js and ts files.
> eslint-config: Disable naming-convention rule for non-js and non-ts files.

- config/generateBabelConfig.js
- package.json
- packages/eslint-config/index.js
- packages/eslint-config/package.json
- packages/kerosene/src/datetime/getCalendarWeeks.ts
- typings/rollup-pugin-babel.d.ts
- yarn.lock
Adds lint rules:
Also replaces unmaintained `babel-plugin-lodash`
> eslint-config: Add autofix for type-only imports

- packages/kerosene-ui/package.json
- packages/kerosene-ui/src/components/Boundaries/helpers.ts
- packages/kerosene-ui/src/components/Boundaries/testHelpers.ts
These helpers were originally written for React Query v4, and I missed the rename of `isLoading` -> `isPending`, as `isLoading` was not removed but instead now represents something different. See [React Query docs](https://tanstack.com/query/v5/docs/react/guides/migrating-to-v5#status-loading-has-been-changed-to-status-pending-and-isloading-has-been-changed-to-ispending-and-isinitialloading-has-now-been-renamed-to-isloading).
> kerosene-ui: Fix React Query query helpers - isLoading -> isPending

- packages/kerosene-ui/package.json
- packages/kerosene-ui/src/components/Boundaries/QueriesBoundary.spec.tsx
- packages/kerosene-ui/src/components/Boundaries/QueriesBoundary.tsx
Simply re-orders the error/loading check to fix an issue where a dependant query would cause a persistent loading fallback when the first query failed.
> kerosene-ui: Prefer rendering error fallback over loading fallback in QueriesBoundary.

- packages/kerosene-test/package.json
- packages/kerosene-ui/package.json
- packages/kerosene/package.json
- packages/kerosene/src/datetime/isAfterDay.ts
- packages/kerosene/src/datetime/isBeforeDay.ts
- packages/kerosene/src/datetime/isSameOrAfterDay.ts
- packages/kerosene/src/datetime/isSameOrBeforeDay.ts
- yarn.lock
Updates `date-fns` to v4 for `@date-fns/tz` support. Also adds `options` to functions that can be timezone-aware.
See also: https://blog.date-fns.org/v40-with-time-zone-support/
> kerosene: Update date-fns to v4 for @date-fns/tz support via options

- package.json
- packages/eslint-config/package.json
- packages/kerosene-test/package.json
- packages/kerosene-test/readme.md
- packages/kerosene-test/src/index.ts
- packages/kerosene-test/src/react/reactQuery.ts
- packages/kerosene-ui/package.json
- packages/kerosene-ui/readme.md
- packages/kerosene-ui/src/components/Boundaries/QueriesBoundary.spec.tsx
- packages/kerosene-ui/src/components/Boundaries/QueryBoundary.spec.tsx
- packages/kerosene-ui/src/hooks/useIsOnline.spec.ts
- packages/kerosene-ui/src/hooks/useIsOnline.ts
- packages/kerosene-ui/src/hooks/usePrevious.ts
- packages/kerosene-ui/src/index.ts
- packages/kerosene/package.json
- packages/kerosene/readme.md
- packages/kerosene/src/error/catchAbortError.spec.ts
- packages/kerosene/src/error/catchAbortError.ts
- packages/kerosene/src/error/isAbortError.spec.ts
- packages/kerosene/src/error/isAbortError.ts
- packages/kerosene/src/index.ts
- packages/kerosene/src/iterable/intersects.spec.ts
- packages/kerosene/src/iterable/intersects.ts
- packages/rollup-plugin-resolve-externals/package.json
- patches/jest-environment-jsdom++jsdom+20.0.3.patch
- testSetup.ts
- yarn.lock
> Various new features: catchAbortError, isAbortError, intersects, useIsOnline, React Query mock helpers
