- readme.md
> improve docs with links to live packages

- packages/kerosene-feature-flags/readme.md
- packages/kerosene-ui/readme.md
- readme.md
> Updating all the readmes

- .travis.yml
- packages/kerosene-feature-flags/package.json
> update build step for master, and bumped flags version

- packages/kerosene/package.json
- readme.md
> Bump @kablamo/kerosene version

- packages/kerosene/readme.md
- packages/kerosene/src/index.ts
- packages/kerosene/src/math/toRadians.spec.ts
- packages/kerosene/src/math/toRadians.ts
> kerosene: Add toRadians function

- packages/kerosene/readme.md
- packages/kerosene/src/array/index.ts
- packages/kerosene/src/array/product.spec.ts
- packages/kerosene/src/array/product.ts
- testSetup.ts
> kerosene: Add product method to calculate cartesian product of arrays

- packages/kerosene/readme.md
- packages/kerosene/src/index.ts
- packages/kerosene/src/math/toSignificantFigures.spec.ts
- packages/kerosene/src/math/toSignificantFigures.ts
> kerosene: add toSignificantFigures method

- packages/kerosene-test/package.json
- packages/kerosene-test/readme.md
- packages/kerosene-test/src/index.ts
- packages/kerosene-test/src/jest/index.ts
- packages/kerosene-test/src/react/createStubComponent.tsx
- packages/kerosene-test/src/react/createStubContext.ts
- packages/kerosene-test/src/sinon/index.ts
- packages/kerosene-test/src/stubs/createStubStyles.ts
- packages/kerosene-test/src/stubs/stubProperties.ts
- packages/kerosene-test/tsconfig.json
- yarn.lock
Adds a new package `@kablamo/kerosene-test` for testing-related functions and types.
> kerosene-test

- packages/kerosene-test/package.json
- packages/kerosene-test/readme.md
- packages/kerosene-test/src/stubs/stubProperties.ts
- packages/kerosene-ui/package.json
- packages/kerosene/package.json
- readme.md
- yarn.lock
> Update readme, fix bugs and bump versions

- packages/kerosene-ui/package.json
- packages/kerosene-ui/src/hooks/useKonamiCode.ts
- packages/kerosene-ui/src/hooks/usePopup.ts
- packages/kerosene/package.json
- packages/kerosene/src/array/contains.ts
- packages/kerosene/src/array/product.ts
- packages/kerosene/src/array/remove.ts
- packages/kerosene/src/array/toggle.ts
Adjusts the typings for functions which accept arrays as inputs to allow readonly arrays as inputs.
> kerosene: Allow functions requiring array inputs to accept readonly arrays

- packages/kerosene-ui/readme.md
> kerosene-ui: Update docs for useRect to match implementation

- .github/workflows/nodejs.yml
> Adding Build and Test checks

- packages/eslint-plugin/package.json
- packages/kerosene-ui/package.json
- packages/kerosene-ui/src/hooks/usePageVisibility.ts
> fixing the usePageVisibility triggering renders multiple times

- packages/eslint-plugin/package.json
- packages/eslint-plugin/src/index.js
- yarn.lock
The recommended config was wrong, the values were the wrong way around.
This works now.
> Fixed eslint-plugin config

- packages/eslint-config/index.js
- packages/eslint-config/package.json
Fixes some common issues in `*.d.ts` files, and a number of other false positives and less helpful errors according to some usage on internal projects.
> eslint-config: Additional fixes

- package.json
- packages/kerosene-test/package.json
- packages/kerosene-ui/package.json
- packages/kerosene-ui/readme.md
- packages/kerosene-ui/src/hooks/useAbortController.spec.tsx
- packages/kerosene-ui/src/hooks/useAbortController.ts
- packages/kerosene-ui/src/hooks/useMergedRefs.spec.tsx
- packages/kerosene-ui/src/hooks/useMergedRefs.ts
- packages/kerosene-ui/src/index.ts
- packages/kerosene-ui/src/utils/waitForRepaint.spec.ts
- packages/kerosene-ui/src/utils/waitForRepaint.ts
- packages/kerosene/package.json
- packages/kerosene/readme.md
- packages/kerosene/src/function/timeout.spec.ts
- packages/kerosene/src/function/timeout.ts
- tsconfig.json
- yarn.lock
Also updates `timeout(delay, { signal? }?)`, `waitForRepaint({ signal? }?)` to accept an `AbortSignal`
> kerosene-ui: Add new hooks useAbortController, useMergedRefs

- packages/kerosene/package.json
- packages/kerosene/src/string/getRandomString.spec.ts
- yarn.lock
Uses `seed-random` to prevent flakey tests breaking the build
> kerosene: Fix flakey test

- package.json
- packages/kerosene-ui/package.json
- packages/kerosene/package.json
- packages/kerosene/readme.md
- packages/kerosene/src/index.ts
- packages/kerosene/src/promise/mapSeries.spec.ts
- packages/kerosene/src/promise/mapSeries.ts
- yarn.lock
> kerosene: Add mapSeries promise util

- packages/kerosene-test/package.json
- packages/kerosene-ui/package.json
- packages/kerosene-ui/readme.md
- packages/kerosene-ui/src/index.ts
- packages/kerosene-ui/src/utils/svg.spec.ts
- packages/kerosene-ui/src/utils/svg.ts
- packages/kerosene/package.json
- packages/kerosene/readme.md
- packages/kerosene/src/index.ts
- packages/kerosene/src/math/toDegrees.ts
- packages/kerosene/src/math/toRadians.ts
- packages/kerosene/src/math/types.ts
- packages/kerosene/src/types/index.spec.ts
- packages/kerosene/src/types/index.ts
Adds a bunch of utility types and SVG utilities
> kerosene, kerosene-ui: Add SVG utilities and extra utility types

- packages/kerosene-ui/package.json
- packages/kerosene-ui/src/components/Boundaries/QueryBoundary.tsx
> kerosene-ui: Fix QueryBoundary - isLoading -> isPending
